import { chromium } from 'playwright-core';
import path from 'path';
import url from 'url';
const f = url.pathToFileURL(path.resolve('POS Balam (offline).html')).href;
const b = await chromium.launch({ channel: 'chrome', headless: true });
const p = await b.newPage({ viewport: { width: 1440, height: 2000 } });
const errs = [];
p.on('pageerror', e => errs.push(e.message));
await p.goto(f, { waitUntil: 'load' });
await p.waitForTimeout(5000);
await p.screenshot({ path: 'shot-dashboard.png', fullPage: true });
console.log('shot ok, errs:', errs.length);
errs.slice(0,5).forEach(e=>console.log(e.slice(0,160)));
await b.close();
